Skip test that fails on 32 bit
======================================================================
ERROR: test_dom_load (calibre.scraper.simple.find_tests.<locals>.TestSimpleWebEngineScraper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/calibre-5.41.0/src/calibre/scraper/simple.py", line 154, in test_dom_load
    html = overseer.fetch_url(url, 'test')
  File "/builddir/build/BUILD/calibre-5.41.0/src/calibre/scraper/simple.py", line 86, in fetch_url
    raise ValueError(output['err'])
ValueError: Failed to load HTML from: file:///builddir/build/BUILD/calibre-5.41.0/resources/templates/new_book.html
----------------------------------------------------------------------

(cherry picked from commit 6738fe68ff08c145c757f71cbd87fdb6a3949fd6)